# This Makefile has been generated by the packaging/configure script. DO NOT
# modify it manually. If you want to modify the Makefile model, modify the
# packaging/Makefile.in file
NAME=lol
VERSION=1.0
MAINTAINER=shifsh
PACKAGENAME=lol
PACKAGETYPE=deb
URL=
ARCH=all
DEPENDS=
MAINTAINER=shifsh
DESCRIPTION=
POSTINST=
PREINST=
POSTRM=
PRERM=
DEBCONFCONFIG=
DEBCONFTEMPLATE=
CONFIGFILE=
TEMPLATEDIR=templates
TMP=/tmp
ENV=
PTMP=$(TMP)/$(PACKAGENAME)

all: package

clean:
	rm -rf $(PTMP)

structure: clean
	mkdir -p $(PTMP)/src $(PTMP)/build $(PTMP)/misc
	rsync -rl --exclude packaging --exclude Makefile \
		--exclude packaging_config.php --exclude '.git*' --exclude '.svn' \
		--exclude '.CVS' --exclude "$(TMP)" . $(PTMP)/src

template: structure
	./packaging/template $(PTMP)/src/$(TEMPLATEDIR) $(ENV)

build: template
	mkdir -p $(PTMP)/build/var/www/lol
	rsync -a --exclude /templates  $(PTMP)/src/* $(PTMP)/build/var/www/lol

package: build
	fpm -s dir -t $(PACKAGETYPE) -n "$(PACKAGENAME)" -v "$(VERSION)" -m "$(MAINTAINER)" --url "$(URL)" \
		--description "$(DESCRIPTION)" $(DEPENDS) $(POSTINST) $(PREINST) $(POSTRM) $(PRERM) \
		$(DEBCONFCONFIG) \
		$(DEBCONFTEMPLATE) \
		$(CONFIGFILE) \
		-a $(ARCH) -C $(PTMP)/build -p $(PTMP)/$(PACKAGENAME)_$(VERSION)_$(ARCH).$(PACKAGETYPE) .

